<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{

    public function findLatest($num)
    {
        $qb = $this->getEntityManager()->getRepository('AppBundle:Post')
            ->createQueryBuilder('p')
            ->orderBy('p.publishedAt', 'desc')->setMaxResults($num);

        return $qb->getQuery()->getResult();

    }

    public function findPostCategory()
    {
        $qb = $this->getEntityManager()->createQueryBuilder('p');
        $qb->join('p.categories', 'categories')
            ->getQuery()
            ->getResult();
//            ->createQuery(
//                'SELECT p, c FROM AppBundle:Post p
//                JOIN p.categories c WHERE p.id = c.id'
//            )
//            ->setMaxResults(5)
//            ->getResult();

        return $qb;
    }

}
