fos_user:
    resource: routing/fos/user.yml

app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_blog:
    path:    /blog
    defaults: { _controller: AppBundle:Post:index }

app_blog_show:
    path:    /blog/{slug}
    defaults: { _controller: AppBundle:Post:show }

app_facebook_connect:
    path: /connect/facebook
    defaults: { _controller: AppBundle:Facebook:login }

app_facebook_connect_callback:
    path: /connect/facebook/callback
    defaults: { _controller: AppBundle:Facebook:loginCallback }
