imports:
    - { resource: services/commonmark.yml }

services:
   postmanager:
       class: AppBundle\Service\PostManager
       arguments:
          - @doctrine.orm.entity_manager

   pagemanager:
       class: AppBundle\Service\PageManager
       arguments:
          - @doctrine.orm.entity_manager

   facebook:
       class: AppBundle\Service\Facebook
       arguments:
          - "@session"
          - app_id: "%facebook_app_id%"
            app_secret: "%facebook_app_secret%"
            default_graph_version: "%facebook_graph_version%"
            default_access_token: "@=service('session').get('facebook_access_token')"